// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8EhrPrsFU-TcfddhJlBi8FMla1dLHaX4',
    appId: '1:843411894574:web:da78351762bf4ba8718abf',
    messagingSenderId: '843411894574',
    projectId: 'english-app-9c856',
    authDomain: 'english-app-9c856.firebaseapp.com',
    storageBucket: 'english-app-9c856.appspot.com',
    measurementId: 'G-HX5JL2B3PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcCT01PpcYDmZOytvlbaDai4qwrUX_qmg',
    appId: '1:843411894574:android:9e105ee4aa8f6807718abf',
    messagingSenderId: '843411894574',
    projectId: 'english-app-9c856',
    storageBucket: 'english-app-9c856.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjPLs37DGoR14uRrJywmeYHtZmQio3c10',
    appId: '1:843411894574:ios:e6932d802f80d84c718abf',
    messagingSenderId: '843411894574',
    projectId: 'english-app-9c856',
    storageBucket: 'english-app-9c856.appspot.com',
    iosClientId: '843411894574-3ai58qojcri8orsto0bi420sntovbub6.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjPLs37DGoR14uRrJywmeYHtZmQio3c10',
    appId: '1:843411894574:ios:0635a25dc975e04e718abf',
    messagingSenderId: '843411894574',
    projectId: 'english-app-9c856',
    storageBucket: 'english-app-9c856.appspot.com',
    iosClientId: '843411894574-97d1nk0oers03151f481l5eks3lvcevg.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishApp.RunnerTests',
  );
}
