/*
import 'package:flutter/material.dart';
//First APP GITHUB TESTS
void main() => runApp(MaterialApp(
  home: Scaffold()
));
*/


import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          HomeScreen(),
        ]),
      ),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFF5F1E3)),
          child: Stack(
            children: [
              Positioned(
                left: 133,
                top: 504,
                child: SizedBox(
                  width: 124,
                  height: 27,
                  child: Text(
                    'Get Started',
                    style: TextStyle(
                      color: Color(0xFFFFF8F8),
                      fontSize: 20,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: -55,
                top: 62,
                child: Container(
                  width: 500,
                  height: 500,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 500,
                          height: 500,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/500x500"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 171,
                        top: 300,
                        child: SizedBox(
                          width: 159,
                          height: 43,
                          child: Text(
                            '  The Best Way                              to Learn English',
                            style: TextStyle(
                              color: Color(0xFF323941),
                              fontSize: 16,
                              fontFamily: 'PT Mono',
                              fontWeight: FontWeight.w400,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
